#
# This is ONLY for local development.
#

services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5440:5432
    volumes:
      - ${PWD}/.data/postgres16
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password